### ISSUE TITLE
Calendário / bug

### ISSUE THREAD

**Issue by yubathom** [SPURB/apropriacaohoras#29]
Tem um bug no calendário:
![grafico08](https://user-images.githubusercontent.com/4117768/81639003-152ea000-93f1-11ea-9a48-09bd2c8bf06c.gif)

Os dias não devem ser ativados sem a ação do usuário. No exemplo acima, o comportamento esperado seria a seleção apenas dos dias: 1, 4 e 5  de maio.  

Para arrumar acredito que seja necessário fazer com que a alteração do mês verifique os dias ativados pelo usuário e renderizar de acordo.  
> incluí o [momentjs](https://momentjs.com/), dependendo pode ser útil para esta refatoração

**Comment by m-dantas** [comment]
@yubathom beleza, vou resolver isso hoje.
