### ISSUE TITLE
bug: permitindo duplicidade de nomes

### ISSUE THREAD

**Issue by m-dantas** [SPURB/apropriacaohoras#43]
Atualizar na API a exceção de não registrar com um nome que já existe no banco de dados.
![Screenshot_12](https://user-images.githubusercontent.com/45770805/83187185-26232500-a104-11ea-842c-2497403fd15f.png)

**Comment by m-dantas** [comment]
Resolve na dev/api, commit https://github.com/SPURB/apropriacaohoras/commit/9ffa2029c7030c8fa7f86694949e6a936f589508

**Comment by yubathom** [comment]
em revisão em #49
