### ISSUE TITLE
feat: grupos de projetos

### ISSUE THREAD

**Issue by yubathom** [SPURB/apropriacaohoras#60]
Admins devem atribuir grupos de projetos que, por sua vez, definem conjuntos de fases e subatividades. Requisitos:
 - Todo projeto deve pertencer a um grupo
 - Cada grupo deve ter um conjunto de fases e subatividades (um preset)
 - A definição de um grupo deve ser feita no momento de criação do projeto

**Comment by yubathom** [comment]
@m-dantas, não fiz o update (__editar grupos__ descrito acima) desta issue. Se puder toca isso amanhã. Tem uma store para grupos `store/admin/grupos`.

Pode criar uma action `updateGrupo` e atualiza a página do formulário em `pages/admin/grupos.vue`. Talvez criar um novo componente para não embolar muito o `components/router-links/CardHorizonal`. Talvez criar subcomponentes.. mas cuidado pois ele é usado também no `admin/index`

A api e as outas funcionalidades descritas aqui estão ok. Seria bom já deixar atualizado os testes de atualização deste recurso. Desta forma:
 - [ ] Criar formulário de update de grupos
 - [ ] Atualizar testes de integração com criação, edição, e filtros (`/admin/grupos?grupo=:id...`) de projetos e fases por cada grupo

**Comment by m-dantas** [comment]
@yubathom fecho então amanhã, vou iniciar esse.

**Comment by yubathom** [comment]
resolvido em #68
