### ISSUE TITLE
Bug ao renderizar o calendário

### ISSUE THREAD

**Issue by m-dantas** [SPURB/apropriacaohoras#7]
Calendário retornando os dias errado.
Exemplo:
Dia 20/03/2020 é uma sexta, no calendário ele renderiza no sábado
![Screenshot_2](https://user-images.githubusercontent.com/45770805/77208324-52a23b80-6ada-11ea-8cd2-e94b2e547c2c.png)

**Comment by yubathom** [comment]
@m-dantas, te enviei uma mensagem no whatsapp e telegram. Veja lá.

**Comment by yubathom** [comment]
@m-dantas,

endpoint provisório para desenvolvimento
[https://api-apropriacaohoras.herokuapp.com/](https://api-apropriacaohoras.herokuapp.com/)

ignore a porta.. ex
[https://api-apropriacaohoras.herokuapp.com/projetos](https://api-apropriacaohoras.herokuapp.com/projetos)

**Comment by m-dantas** [comment]
Solução já adicionada em produção [#11 ](url)
